const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('thor', {
  status: () => ipcRenderer.invoke('thor:status'),
  enroll: (payload) => ipcRenderer.invoke('thor:enroll', payload),
  sync: () => ipcRenderer.invoke('thor:sync'),
  searchProducts: (query) => ipcRenderer.invoke('thor:search-products', query),
  customers: (query) => ipcRenderer.invoke('thor:customers', query),
  quoteSale: (items, discount = 0) => ipcRenderer.invoke('thor:quote-sale', items, discount),
  openCash: (payload) => ipcRenderer.invoke('thor:open-cash', payload),
  cashMovement: (payload) => ipcRenderer.invoke('thor:cash-movement', payload),
  closeCash: (payload) => ipcRenderer.invoke('thor:close-cash', payload),
  finalizeSale: (payload) => ipcRenderer.invoke('thor:finalize-sale', payload),
  cancelSale: (payload) => ipcRenderer.invoke('thor:cancel-sale', payload),
  returnSale: (payload) => ipcRenderer.invoke('thor:return-sale', payload),
  requestNfce: (payload) => ipcRenderer.invoke('thor:request-nfce', payload),
  fiscalSales: (query = '') => ipcRenderer.invoke('thor:fiscal-sales', query),
  fiscalSale: (key) => ipcRenderer.invoke('thor:fiscal-sale', key),
  printers: () => ipcRenderer.invoke('thor:printers'),
  serialPorts: () => ipcRenderer.invoke('thor:serial-ports'),
  settings: () => ipcRenderer.invoke('thor:settings'),
  saveSettings: (settings) => ipcRenderer.invoke('thor:save-settings', settings),
  setPrinter: (name) => ipcRenderer.invoke('thor:set-printer', name),
  printSale: (saleKey, type = 'pre_sale') => ipcRenderer.invoke('thor:print-sale', saleKey, type),
  printLast: () => ipcRenderer.invoke('thor:print-last'),
});
