'use client';

import { useEffect, useState } from 'react';
import { erpCashClose, erpCashList, erpCashOpen } from './actions';

type Row=Record<string,unknown>;
const money=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v??0));
const dt=(v:unknown)=>v?new Date(String(v)).toLocaleString('pt-BR'):'—';

export function CashWorkspace({posRegisters}:{posRegisters:Row[]}){
 const [sessions,setSessions]=useState<Row[]>([]);const [pos,setPos]=useState(String(posRegisters[0]?.id??''));const [opening,setOpening]=useState(0);const [counted,setCounted]=useState<Record<string,string>>({});const [message,setMessage]=useState('');const [loading,setLoading]=useState(false);
 async function load(){const r=await erpCashList();if(r.ok)setSessions(r.data);else setMessage(String(r.error??'Falha ao carregar caixa'))}
 useEffect(()=>{void load()},[]);
 async function open(){if(!pos)return;setLoading(true);const r=await erpCashOpen(pos,opening);setLoading(false);if(r.ok){setMessage('Caixa aberto. As próximas vendas da filial serão vinculadas automaticamente a esta sessão.');setOpening(0);await load()}else setMessage(String(r.error??'Falha ao abrir caixa'))}
 async function close(id:string){const raw=counted[id];if(raw===undefined||raw===''){setMessage('Informe o valor contado para fechar o caixa.');return}setLoading(true);const r=await erpCashClose(id,Number(raw),'Fechamento pelo ThorPDV');setLoading(false);if(r.ok){const diff=Number(r.difference??0);setMessage(`Caixa fechado. Esperado: ${money(r.expected)} · Contado: ${money(r.closing)} · Diferença: ${money(diff)}.`);await load()}else setMessage(String(r.error??'Falha ao fechar caixa'))}
 const openCount=sessions.filter(s=>s.status==='open').length;const sales=sessions.reduce((a,s)=>a+Number(s.sales_total??0),0);const received=sessions.reduce((a,s)=>a+Number(s.received_total??0),0);
 return <div className="erp-cash-workspace"><section className="erp-module-kpis"><article><span>PDVs cadastrados</span><strong>{posRegisters.filter(p=>p.active!==false).length}</strong><small>terminais ativos</small></article><article><span>Caixas abertos</span><strong>{openCount}</strong><small>sessões em operação</small></article><article><span>Vendas nas sessões</span><strong>{money(sales)}</strong><small>faturamento vinculado</small></article><article><span>Recebido</span><strong>{money(received)}</strong><small>pagamentos das sessões</small></article></section><section className="erp-module-card"><div className="erp-cash-open"><div><h2>Abertura de caixa</h2><p>Selecione um terminal e informe o fundo inicial.</p></div><label>PDV<select value={pos} onChange={e=>setPos(e.target.value)}><option value="">Selecione...</option>{posRegisters.filter(p=>p.active!==false).map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.name)} · {String(p.branch??'')}</option>)}</select></label><label>Fundo inicial<input type="number" min="0" step="0.01" value={opening} onChange={e=>setOpening(Number(e.target.value))}/></label><button className="erp-primary" disabled={!pos||loading} onClick={open}>Abrir caixa</button></div>{message&&<p className="erp-message">{message}</p>}<div className="erp-table-scroll"><table className="erp-data-table"><thead><tr><th>PDV</th><th>Filial</th><th>Abertura</th><th>Fundo</th><th>Vendas</th><th>Recebido</th><th>Dinheiro</th><th>Esperado em espécie</th><th>Status</th><th>Fechamento</th></tr></thead><tbody>{sessions.length===0?<tr><td className="erp-empty" colSpan={10}>Nenhuma sessão de caixa registrada.</td></tr>:sessions.map((s,i)=><tr key={String(s.id??i)}><td><strong>{String(s.pos??'')}</strong></td><td>{String(s.branch??'')}</td><td>{dt(s.opened_at)}</td><td>{money(s.opening_amount)}</td><td>{money(s.sales_total)}</td><td>{money(s.received_total)}</td><td>{money(s.cash_received)}</td><td><strong>{money(s.expected_cash)}</strong></td><td><span className={`erp-pill ${s.status==='open'?'':'danger'}`}>{String(s.status)}</span></td><td>{s.status==='open'?<div className="erp-cash-close"><input type="number" step="0.01" placeholder="Valor contado" value={counted[String(s.id)]??''} onChange={e=>setCounted(c=>({...c,[String(s.id)]:e.target.value}))}/><button className="erp-row-action" disabled={loading} onClick={()=>close(String(s.id))}>Fechar</button></div>:<span>{money(s.closing_amount)}<small>{s.closed_at?` · ${dt(s.closed_at)}`:''}</small></span>}</td></tr>)}</tbody></table></div></section></div>;
}
