'use client';

import { FormEvent, useState } from 'react';
import { erpFiscalPrepare, erpFiscalSend, erpFiscalSettingsSave, erpLoad } from './actions';

type Row=Record<string,unknown>;
const money=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v??0));
const dt=(v:unknown)=>v?new Date(String(v)).toLocaleString('pt-BR'):'—';

export function FiscalWorkspace({initialDocs,sales,settings,preselect='nfe'}:{initialDocs:Row[];sales:Row[];settings:Row;preselect?:'nfe'|'nfce'}){
 const [docs,setDocs]=useState(initialDocs);const [sale,setSale]=useState('');const [docType,setDocType]=useState<'nfe'|'nfce'>(preselect);const [message,setMessage]=useState('');const [errors,setErrors]=useState<string[]>([]);const [provider,setProvider]=useState(String(settings.provider??''));const [environment,setEnvironment]=useState(String(settings.environment??'homologation'));const [nfeSeries,setNfeSeries]=useState(String(settings.nfe_series??'1'));const [nfceSeries,setNfceSeries]=useState(String(settings.nfce_series??'1'));
 async function refresh(){const r=await erpLoad('fiscal_documents');if(r.ok)setDocs(r.data)}
 async function saveSettings(e:FormEvent){e.preventDefault();const r=await erpFiscalSettingsSave({provider,environment,nfe_series:nfeSeries,nfce_series:nfceSeries});setMessage(r.ok?'Configuração fiscal salva. As credenciais secretas do provedor ainda precisam ser configuradas em ambiente seguro.':String(r.error??'Falha ao salvar configuração'));}
 async function prepare(){if(!sale)return;const r=await erpFiscalPrepare(sale,docType);if(r.ok){const list=(r.validation_errors as string[]|undefined)??[];setErrors(list);setMessage(list.length?`Rascunho ${docType.toUpperCase()} criado com ${list.length} pendência(s).`:`Rascunho ${docType.toUpperCase()} validado e pronto para envio quando as credenciais estiverem disponíveis.`);setSale('');await refresh();}else setMessage(`Não foi possível preparar: ${String(r.error??'erro')}`);}
 async function send(id:string){const r=await erpFiscalSend(id);if(r.ok)setMessage('Documento enviado.');else{const list=(r.validation_errors as string[]|undefined)??[];setErrors(list);setMessage(r.error==='provider_credentials_required'?`Documento validado, mas falta a credencial segura do provedor ${String(r.provider??'fiscal')}.`:`Transmissão não realizada: ${String(r.error??'erro')}`)}}
 return <div className="erp-fiscal-grid"><section className="erp-module-card erp-advanced-panel"><h2>Configuração fiscal</h2><p>Configurações públicas. Token, certificado e segredo do provedor nunca são gravados neste formulário.</p><form className="erp-form-grid" onSubmit={saveSettings}><label>Provedor<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="">Não configurado</option><option value="focusnfe">Focus NFe</option><option value="nuvemfiscal">Nuvem Fiscal</option><option value="plugnotas">PlugNotas</option></select></label><label>Ambiente<select value={environment} onChange={e=>setEnvironment(e.target.value)}><option value="homologation">Homologação</option><option value="production">Produção</option></select></label><label>Série NF-e<input value={nfeSeries} onChange={e=>setNfeSeries(e.target.value)}/></label><label>Série NFC-e<input value={nfceSeries} onChange={e=>setNfceSeries(e.target.value)}/></label><button className="erp-primary">Salvar configuração</button></form></section><section className="erp-module-card erp-advanced-panel"><h2>Preparar documento</h2><p>O ThorPDV cria o snapshot fiscal da venda e identifica pendências antes de qualquer transmissão.</p><label>Venda<select value={sale} onChange={e=>setSale(e.target.value)}><option value="">Selecione uma venda...</option>{sales.filter(s=>s.status==='completed').map(s=><option value={String(s.id)} key={String(s.id)}>Venda #{String(s.number)} · {String(s.customer??'Consumidor')} · {money(s.total)}</option>)}</select></label><label>Documento<select value={docType} onChange={e=>setDocType(e.target.value as 'nfe'|'nfce')}><option value="nfe">NF-e</option><option value="nfce">NFC-e</option></select></label><button className="erp-primary" disabled={!sale} onClick={prepare}>Validar e criar rascunho</button>{errors.length>0&&<div className="erp-fiscal-errors"><strong>Pendências</strong>{errors.map((x,i)=><span key={i}>• {x}</span>)}</div>}</section>{message&&<div className="erp-message erp-fiscal-message">{message}</div>}<section className="erp-module-card erp-fiscal-docs"><div className="erp-table-scroll"><table className="erp-data-table"><thead><tr><th>Data</th><th>Tipo</th><th>Número</th><th>Série</th><th>Ambiente</th><th>Status</th><th>Chave</th><th>Provedor</th><th>Ação</th></tr></thead><tbody>{docs.length===0?<tr><td colSpan={9} className="erp-empty">Nenhum documento fiscal preparado.</td></tr>:docs.map((d,i)=><tr key={String(d.id??i)}><td>{dt(d.created_at)}</td><td>{String(d.document_type).toUpperCase()}</td><td>{String(d.number??'—')}</td><td>{String(d.series??'—')}</td><td>{String(d.environment)}</td><td><span className={`erp-pill ${d.status==='rejected'?'danger':''}`}>{String(d.status)}</span></td><td>{String(d.access_key??'—')}</td><td>{String(d.provider??'—')}</td><td>{d.status==='draft'?<button className="erp-row-action" onClick={()=>send(String(d.id))}>Transmitir</button>:'—'}</td></tr>)}</tbody></table></div></section></div>;
}
