'use client';

import { FormEvent, useState } from 'react';
import { erpSave } from './actions';

type Row=Record<string,unknown>;
const dt=(v:unknown)=>v?new Date(String(v)).toLocaleString('pt-BR'):'—';
const cash=(v:unknown)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v??0));

export function StockWorkspace({products,history,mode='all'}:{products:Row[];history:Row[];mode?:'all'|'adjustment'}){
 const [product,setProduct]=useState('');const [type,setType]=useState(mode==='adjustment'?'adjustment':'in');const [qty,setQty]=useState(1);const [cost,setCost]=useState(0);const [notes,setNotes]=useState('');const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
 const rows=mode==='adjustment'?history.filter(r=>r.movement_type==='adjustment'):history;
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);const r=await erpSave('stock',{product_id:product,movement_type:mode==='adjustment'?'adjustment':type,quantity:qty,unit_cost:cost||null,notes});setSaving(false);if(r.ok){setMessage('Movimentação registrada e saldo atualizado.');location.reload();}else setMessage(`Não foi possível registrar: ${String(r.error??'erro')}`);}
 return <section className="erp-module-card"><div className="erp-advanced-head"><h2>{mode==='adjustment'?'Ajuste de estoque':'Movimentações de estoque'}</h2><p>Entradas, saídas e perdas validam e atualizam o saldo. Transferências usam a aba específica para registrar origem e destino.</p></div><form className="erp-form-grid erp-advanced-form" onSubmit={submit}><label>Produto<select required value={product} onChange={e=>setProduct(e.target.value)}><option value="">Selecione...</option>{products.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.name)} — saldo {String(p.stock??0)}</option>)}</select></label>{mode!=='adjustment'&&<label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="in">Entrada</option><option value="out">Saída</option><option value="loss">Perda</option><option value="adjustment">Ajuste</option></select></label>}<label>Quantidade {mode==='adjustment'?'(+ ou -)':''}<input required type="number" step="0.001" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>Custo unitário<input type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label className="wide">Motivo / documento<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="NF de entrada, perda, acerto..."/></label><button className="erp-primary" disabled={saving}>{saving?'Salvando...':'Registrar movimentação'}</button></form>{message&&<p className="erp-message">{message}</p>}<div className="erp-table-scroll"><table className="erp-data-table"><thead><tr><th>Data</th><th>Produto</th><th>Código</th><th>Tipo</th><th>Quantidade</th><th>Custo</th><th>Filial</th><th>Observação</th></tr></thead><tbody>{rows.length===0?<tr><td className="erp-empty" colSpan={8}>Nenhuma movimentação registrada.</td></tr>:rows.map((r,i)=><tr key={String(r.id??i)}><td>{dt(r.created_at)}</td><td>{String(r.product??'')}</td><td>{String(r.sku??'—')}</td><td><span className="erp-pill">{String(r.movement_type)}</span></td><td>{String(r.quantity??0)}</td><td>{r.unit_cost?cash(r.unit_cost):'—'}</td><td>{String(r.branch??'')}</td><td>{String(r.notes??'—')}</td></tr>)}</tbody></table></div></section>;
}
