const app=document.getElementById('app');
let state={status:null,products:[],cart:[],payment:'cash',query:'',busy:false};
const money=(v)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

async function boot(){ state.status=await window.thor.status(); render(); if(state.status.enrolled){ await refreshProducts(''); setInterval(refreshStatus,3000); } }
async function refreshStatus(){ state.status=await window.thor.status(); updateTop(); }
async function refreshProducts(q=state.query){ state.query=q; state.products=await window.thor.searchProducts(q); renderProducts(); }
function total(){ return state.cart.reduce((s,i)=>s+i.quantity*i.unitPrice,0); }

function render(){ if(!state.status?.enrolled) return renderSetup(); app.innerHTML=`<div class="shell"><header class="topbar"><div class="top-left"><div class="logo">ϟ THOR<b>PDV</b></div><span id="context"></span></div><div class="top-right"><span id="queue" class="queue"></span><span id="status" class="status"><i></i><b></b></span><button class="secondary" id="sync">Sincronizar</button><button class="secondary" id="hardware">Impressora</button></div></header><main class="work"><section class="catalog"><div class="search-row"><input id="search" class="search" placeholder="Código de barras, SKU ou descrição..." autofocus><button class="secondary" id="cash">Caixa</button></div><div id="products" class="products"></div></section><aside class="cart-panel"><div class="cart-head"><div><small>VENDA ATUAL</small><h2>Cupom</h2></div><button class="secondary" id="clear">Limpar</button></div><div id="cart" class="cart"></div><div><div class="totals"><div class="total-row"><span>Itens</span><b id="itemsCount">0</b></div><div class="total-row grand"><span>Total</span><span id="grand">R$ 0,00</span></div></div><div class="payment-methods">${[['cash','Dinheiro'],['pix','PIX'],['debit_card','Débito'],['credit_card','Crédito']].map(([k,n])=>`<button class="pay ${state.payment===k?'active':''}" data-pay="${k}">${n}</button>`).join('')}</div><button class="primary finalize" id="finalize">Finalizar venda (F2)</button></div></aside></main><footer class="bottom"><span>F2 Finalizar • F4 Caixa • F6 Sincronizar • Enter adiciona produto</span><span id="footerSync"></span></footer></div>`; bind(); updateTop(); refreshProducts(''); renderCart(); }
function renderSetup(){ app.innerHTML=`<main class="setup"><section class="setup-card"><div class="brand">ϟ THOR<span>PDV</span></div><h1>Ativar este caixa</h1><p class="muted">No ThorERP Gestão, abra Administrativo → PDV Desktop, escolha o caixa e gere um código de ativação.</p><div class="field"><label>Código de ativação</label><input id="code" maxlength="8" autocomplete="off" placeholder="XXXXXXXX"></div><div class="field"><label>Nome deste terminal</label><input id="name" value="Caixa - ${esc(location.hostname||'Windows')}"></div><button id="activate" class="primary">Ativar e sincronizar</button><div id="setupError"></div></section></main>`; document.getElementById('activate').onclick=async()=>{const b=document.getElementById('activate'),err=document.getElementById('setupError'); try{b.disabled=true;b.textContent='Ativando...'; state.status=await window.thor.enroll({code:document.getElementById('code').value.trim(),name:document.getElementById('name').value.trim()}); render();}catch(e){err.className='error';err.textContent=e.message;}finally{b.disabled=false;b.textContent='Ativar e sincronizar';}}; }
function bind(){ const search=document.getElementById('search'); let timer; search.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>refreshProducts(search.value),120)}; search.onkeydown=e=>{if(e.key==='Enter'&&state.products[0]){add(state.products[0]);search.select();}}; document.getElementById('sync').onclick=async()=>{await window.thor.sync();await refreshStatus();await refreshProducts();}; document.getElementById('clear').onclick=()=>{state.cart=[];renderCart();}; document.getElementById('finalize').onclick=finalize; document.getElementById('cash').onclick=openCashModal; document.getElementById('hardware').onclick=hardwareModal; document.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>{state.payment=b.dataset.pay;document.querySelectorAll('[data-pay]').forEach(x=>x.classList.toggle('active',x===b));}); document.addEventListener('keydown',hotkeys,{once:true}); }
function hotkeys(e){ if(e.key==='F2'){e.preventDefault();finalize();} if(e.key==='F4'){e.preventDefault();openCashModal();} if(e.key==='F6'){e.preventDefault();window.thor.sync().then(refreshStatus);} document.addEventListener('keydown',hotkeys,{once:true}); }
function renderProducts(){ const box=document.getElementById('products'); if(!box)return; box.innerHTML=state.products.length?state.products.map((p,i)=>`<div class="product" data-index="${i}"><div><strong>${esc(p.name)}</strong><small>${esc(p.sku||'Sem SKU')} • ${esc((p.barcodes||[])[0]||'sem EAN')}</small></div><div class="stock">Estoque<br><b>${Number(p.quantity||0).toFixed(3).replace(/\.000$/,'')}</b></div><div class="price">${money(p.base_price)}</div></div>`).join(''):`<div class="empty">Nenhum produto encontrado.</div>`; box.querySelectorAll('.product').forEach(el=>el.onclick=()=>add(state.products[Number(el.dataset.index)])); }
function add(p){ const found=state.cart.find(i=>i.productId===p.id); if(found)found.quantity++; else state.cart.push({productId:p.id,name:p.name,sku:p.sku,quantity:1,unitPrice:Number(p.base_price||p.sale_price||0)}); renderCart(); }
function renderCart(){ const box=document.getElementById('cart');if(!box)return; box.innerHTML=state.cart.length?state.cart.map((i,n)=>`<div class="cart-item"><div><strong>${esc(i.name)}</strong><small>${money(i.unitPrice)} un.</small></div><div class="qty"><button data-minus="${n}">−</button><b>${i.quantity}</b><button data-plus="${n}">+</button></div></div>`).join(''):`<div class="empty">Leia um código de barras ou selecione um produto.</div>`; box.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const i=state.cart[Number(b.dataset.minus)];i.quantity--;if(i.quantity<=0)state.cart.splice(Number(b.dataset.minus),1);renderCart();});box.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{state.cart[Number(b.dataset.plus)].quantity++;renderCart();});document.getElementById('itemsCount').textContent=state.cart.reduce((s,i)=>s+i.quantity,0);document.getElementById('grand').textContent=money(total()); }
async function finalize(){ if(state.busy||!state.cart.length)return; if(!state.status.cashOpenEventId)return openCashModal(); const t=total(); try{state.busy=true;const result=await window.thor.finalizeSale({items:state.cart.map(i=>({productId:i.productId,quantity:i.quantity})),payments:[{method:state.payment,amount:t}]});state.cart=[];renderCart();await refreshProducts();await refreshStatus(); if(confirm(`Venda registrada: ${money(result.total)}.\n\nImprimir comprovante?`)) await window.thor.printLast().catch(e=>alert(`Venda salva. Impressão: ${e.message}`));}catch(e){alert(`Não foi possível finalizar: ${e.message}`);}finally{state.busy=false;} }
function modal(html){ const wrap=document.createElement('div');wrap.className='modal';wrap.innerHTML=`<div class="modal-card">${html}</div>`;document.body.appendChild(wrap);wrap.onclick=e=>{if(e.target===wrap)wrap.remove();};return wrap; }
function openCashModal(){ const opened=state.status.cashOpenEventId; const m=modal(opened?`<h3>Caixa aberto</h3><p class="muted">Você pode lançar suprimento/sangria ou fechar o caixa.</p><div class="field"><label>Valor</label><input id="cashValue" type="number" step="0.01" value="0"></div><div class="actions"><button class="secondary" id="supply">Suprimento</button><button class="secondary" id="withdraw">Sangria</button><button class="danger primary" id="closeCash">Fechar caixa</button></div>`:`<h3>Abrir caixa</h3><p class="muted">Informe o fundo de troco inicial.</p><div class="field"><label>Valor de abertura</label><input id="cashValue" type="number" step="0.01" value="0"></div><div class="actions"><button class="primary" id="openCash">Abrir caixa</button></div>`); if(opened){m.querySelector('#supply').onclick=async()=>{await window.thor.cashMovement({movementType:'supply',amount:Number(m.querySelector('#cashValue').value)});m.remove();refreshStatus();};m.querySelector('#withdraw').onclick=async()=>{await window.thor.cashMovement({movementType:'withdrawal',amount:Number(m.querySelector('#cashValue').value)});m.remove();refreshStatus();};m.querySelector('#closeCash').onclick=async()=>{await window.thor.closeCash({closingAmount:Number(m.querySelector('#cashValue').value)});m.remove();refreshStatus();};}else m.querySelector('#openCash').onclick=async()=>{await window.thor.openCash({openingAmount:Number(m.querySelector('#cashValue').value)});m.remove();refreshStatus();}; }
async function hardwareModal(){ const [printers,ports]=await Promise.all([window.thor.printers().catch(()=>[]),window.thor.serialPorts().catch(()=>[])]);const m=modal(`<h3>Hardware local</h3><div class="field"><label>Impressora térmica</label><select id="printer"><option value="">Selecione...</option>${printers.map(p=>`<option value="${esc(p.Name)}" ${state.status.printer===p.Name?'selected':''}>${esc(p.Name)}</option>`).join('')}</select></div><p class="muted">Portas seriais detectadas: ${ports.map(p=>esc(p.DeviceID)).join(', ')||'nenhuma'}.</p><div class="actions"><button class="primary" id="savePrinter">Salvar</button></div>`);m.querySelector('#savePrinter').onclick=async()=>{await window.thor.setPrinter(m.querySelector('#printer').value);m.remove();refreshStatus();}; }
function updateTop(){ if(!state.status)return; const s=document.getElementById('status'),q=document.getElementById('queue'),ctx=document.getElementById('context'),foot=document.getElementById('footerSync'); if(s){s.className=`status ${state.status.online?'online':'offline'}`;s.querySelector('b').textContent=state.status.syncing?'Sincronizando':state.status.online?'Online':'Offline';} if(q)q.textContent=`Fila: ${state.status.queue?.pending||0} pendente(s)${state.status.queue?.rejected?` • ${state.status.queue.rejected} rejeitado(s)`:''}`; if(ctx)ctx.textContent=`${state.status.context?.branch_name||''} • ${state.status.context?.pos_name||''}`; if(foot)foot.textContent=state.status.lastSyncAt?`Última sincronização: ${new Date(state.status.lastSyncAt).toLocaleTimeString('pt-BR')}`:'Ainda não sincronizado'; }
boot().catch(e=>{app.innerHTML=`<main class="setup"><section class="setup-card"><h1>Falha ao iniciar</h1><div class="error">${esc(e.message)}</div></section></main>`;});
